### ISSUE TITLE
Toolbar expanding a lot in windowed mode

### ISSUE THREAD

**Issue by mateo-sheme** [amnweb/firefox-plus#1]
![Screenshot from 2024-01-21 17-43-26](https://github.com/amnweb/firefox-plus/assets/96703695/aeae4784-4a73-4934-a25d-1366c77c9712)

Just installed the theme, looks pretty good, however I use forge as a an extension and I am all the time in windowed tabs. It is really annoying to have it extended all the time. If I move to full screen the toolbar gets fixed.

![Screenshot from 2024-01-21 17-46-54](https://github.com/amnweb/firefox-plus/assets/96703695/2ecc39a6-1d65-47b1-b740-7688a8adc12e)

Also the font at the tabs titles is really small. From the screenshot it doesn't look much but you can see it on daily usage.

Any way I can fix these 2 problems? Thank you in advance!

**Comment by amnweb** [comment]
I am unable to identify any error or problem. Could you please provide me with more information, such as your operating system and extensions installed in Firefox?

**Comment by mateo-sheme** [comment]
The system I am using is Fedora 39 with Gnome 45.3.

The extensions I am using are : 
dash-to-dock
clipboard-indicator
blur-my-shell
gsconnect
just-perfection-desktop
forge
windowIsReady_Remover
weatheroclock
user-theme
burn-my-windows
compiz-alike-magic-lamp-effect
Rounded_Corners
Vitals
color-picker
desktop-cube
top-bar-organizer
background-logo

The problem happens when I am using it as a windowed panel with forge. The toolbar extends like in the screenshot. If I maximaze it, the toolbar goes back to normal.

**Comment by amnweb** [comment]
Just installed fedora and gnome 45.3 with Forge on my could server to test and I can't find problems

![Screenshot 2024-01-25 222514](https://github.com/amnweb/firefox-plus/assets/16545063/3a599a09-eb65-4a3a-a711-f7f1443c35b6)
![Screenshot 2024-01-25 222745](https://github.com/amnweb/firefox-plus/assets/16545063/28852722-dd10-4c16-8664-1d4cdcfdde98)

**Comment by mateo-sheme** [comment]
Can you also if possible send me a picture with the bookmark toolbar when you extend it?

**Comment by mateo-sheme** [comment]
I think I manged to solve it. I think the theme someway interfered with the firefox's font configs. Take a look at [this](https://support.mozilla.org/en-US/questions/1289717). Go to about:config and change layout.css.devPixelsPerPx to the value what fits your eye and basically fixes both problems I had before. I am closing this, thank you!
