### ISSUE TITLE
Always show X to close tabs on hover

### ISSUE THREAD

**Issue by Toastie** [amnweb/firefox-plus#12]
When I only have a few tabs open the small X to close a tab is shown on hover (similar to the behavior in Chrome). 
Once I open more then 14 Tabs however, the X vanishes and is not shown anymore on hover. Thus requiring the tab to be opened before it can be closed.

I was wondering if there is a setting to always show the X on hover? 
I could not find any such option in user.js

**Comment by amnweb** [comment]
Should be fixed now. Please update chrome files and try again.

**Comment by Toastie** [comment]
Can confirm, the X stays present now.

Thank you for the quick fix!
