### ISSUE TITLE
Tracking protections icon becomes colored when it is blocking things

### ISSUE THREAD

**Issue by MulesGaming** [amnweb/firefox-plus#13]
Not sure if this is intentional but it stands out to much around the other icons. ![image](https://github.com/amnweb/firefox-plus/assets/110064958/03333180-1a4e-4d0f-809f-2692e8630eeb)

**Comment by MulesGaming** [comment]
Here's the relevant css 
![image](https://github.com/amnweb/firefox-plus/assets/110064958/0f166872-647f-45d8-a14e-59643c564fd6)

**Comment by amnweb** [comment]
Which FF version ?

**Comment by MulesGaming** [comment]
128.0b2

**Comment by amnweb** [comment]
This is beta or nightly ? Must wait for stable release before I make any changes

**Comment by MulesGaming** [comment]
Beta

**Comment by amnweb** [comment]
OK, I can see this in 128.0 now. For me, this looks OK, and there is logic to get these icon in different color.
