### ISSUE TITLE
Toolbar buttons "min max close" dont appear or work

### ISSUE THREAD

**Issue by Oztugr** [amnweb/firefox-plus#16]
**Describe the bug**
Toolbar buttons "min max close" dont appear or work. And to fix the problem, when I added the lines as in the same issue closed (#nav-bar:not([tabs-hidden="true"]) {
  position: inherit !important;
}, upper rounded corners broke :(

**To Reproduce**

**Screenshots or video**
Add screenshots or video to help explain your problem.

**Firefox version (please complete the following information):**
 - Version  127.0.2

PS. Also I have noticed Sidebery is supported with Userchrome Toggle Extended and it looks amazing

![Before adding the code](https://github.com/amnweb/firefox-plus/assets/172539137/bdce3caf-3a98-4214-a615-7f897d6094b9)
![After adding the code](https://github.com/amnweb/firefox-plus/assets/172539137/c436b4ce-a72b-4e1c-a027-f81401e91faf)

**Comment by amnweb** [comment]
Can you post your user.js?

**Comment by amnweb** [comment]
OK i think found it, this is related with sidebar. Just tell me when you set `fp.tweak.sidebar-enabled` to `false` you can see buttons ?

**Comment by Oztugr** [comment]
yes it is related to sidebar enabling

**Comment by Oztugr** [comment]
but your previous solution fixes the buttons and breaks round corners

**Comment by amnweb** [comment]
> but your previous solution fixes the buttons and breaks round corners

This was a problem with Firefox Developer Edition I will support only stable release.
Anyway, I will try to solve this problem.

**Comment by Oztugr** [comment]
Thanks ,  looking forward to it

**Comment by amnweb** [comment]
Please update chrome files
