### ISSUE TITLE
Sidebar border not closing automatically

### ISSUE THREAD

**Issue by laughingstar101** [amnweb/firefox-plus#17]
**Describe the bug**
Using the sidebar tabs extension, theres this massive border where the sidebar is supposed to be. It doesn't close automacitally but when I hover the cursor to the side of the screen, the sidebar shows up. When I put the cursor away from the sidebar, the sidebar closes but the border remains.

**To Reproduce**
1. Use Sidebar Tabs extension
2. See error

**Screenshots or video**
[https://imgur.com/a/08yxGNG](url)

**Firefox version (please complete the following information):**
 - Firefox Nightly Version 131.0a1

**Additional context**

**Comment by amnweb** [comment]
Sorry about that, but I don't want to support the Nightly version for many reasons. Anyway, I think the sidebar comes natively in Firefox soon and so maybe it's time to stop support for this extension.
