### ISSUE TITLE
Tabs have gap above them when window is maximized

### ISSUE THREAD

**Issue by BrOstro** [amnweb/firefox-plus#18]
Thanks so much for the theme, it looks great!  

**Describe the bug**
When Firefox is maximized, there seems to be a tiny gap above the tabs which doesn't allow me to quickly click on a tab I'm looking to switch to due to having to be more precise.
**To Reproduce**
1. Install latest firefox-plus.
2. Open a few tabs.
3. Maximize Firefox on top of the other application.
4. Click the top of your screen above a tab and it is expected that the tab itself extends to the top of the window.

**Screenshots or video**

https://github.com/user-attachments/assets/73461547-e104-4390-8f82-f371374f6ce6

**Firefox version (please complete the following information):**
 - 129.0.2 (64-bit)

**Firefox plus version:**
2.0.5

**Additional context**
Can confirm this is due to Firefox-plus as the issue does not occur when not installed.

user.js:

user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("svg.context-properties.content.enabled", true);
user_pref("layout.css.color-mix.enabled", true);
user_pref("layout.css.light-dark.enabled", true);
user_pref("browser.tabs.tabMinWidth", 66);
user_pref("browser.tabs.tabClipWidth", 86);
user_pref("browser.in-content.dark-mode", true);
user_pref("ui.systemUsesDarkTheme", 1);
user_pref("fp.tweak.autohide-bookmarks", false);
user_pref("fp.tweak.macos-button", false);
user_pref("fp.tweak.rounded-corners", true);
user_pref("fp.tweak.sidebar-enabled", false);
user_pref("app.update.auto", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.enabled", true);

**Comment by BrOstro** [comment]
Fixed it locally by deleting 
```#tabbrowser-tabs,
#TabsToolbar #TabsToolbar-customization-target > .toolbarbutton-1 {
	margin-top: var(--tab-block-margin) !important;
}
```
Though not sure if that's going to impact other places so I won't create a PR.

**Comment by amnweb** [comment]
I left it like that on purpose, I use the tiling window manager, and it really looks better when there is a small gap.
Maybe we can make it when is maximized **only** to remove that `margin-top` ?

**Comment by kbc8090** [comment]
I like the gap, however you cant click above the tab to switch to it.  "Material fox updated" has the gap but also allows the mouse to click above the tab (like chrome, edge) and still switch to it.  Not sure the modifications to do that, haven't looked through how it's being done.  Something that would be a good compromise, imo.

**Comment by amnweb** [comment]
> I like the gap, however you cant click above the tab to switch to it. "Material fox updated" has the gap but also allows the mouse to click above the tab (like chrome, edge) and still switch to it. Not sure the modifications to do that, haven't looked through how it's being done. Something that would be a good compromise, imo.

Yeah that is good idea.

**Comment by amnweb** [comment]
This should be fixed in https://github.com/amnweb/firefox-plus/commit/264be0e0150b739d6824d5ddf347c7c19d1265a1
