### ISSUE TITLE
tab clips

### ISSUE THREAD

**Issue by MegaTheLEGEND** [amnweb/firefox-plus#23]
**Describe the bug**

When I am using multiple tabs I tend to put my mouse to the top of the screen to switch tabs. but with this the tab clips do not go to the top of the screen / window an i find it quite hard to line up. is there any way to change this? otherwise it looks really nice!

**Comment by amnweb** [comment]
Can show video or screenshot what you mean ?

**Comment by MulesGaming** [comment]
Not the original reporter but I believe they are referencing this. This is on beta firefox however so it might not affect stable.
![Screenshot_20241107_214231](https://github.com/user-attachments/assets/9ea647d5-1934-4a34-b86b-1e8001ffa3f5)

**Comment by amnweb** [comment]
Should be fixed.
