### ISSUE TITLE
Tab visual issue — Grey Line where inverted corners are

### ISSUE THREAD

**Issue by JoshMuscat** [amnweb/firefox-plus#24]
It's a small issue, but I see a tiny line on the active tab where the inverted corners are. You can see what I mean in the screenshot I have attached. Not sure if this could be fixed with a simple negative bottom margin? This only happens when using a window size that is not full-screen (which I tend to use as full-screen is too large for my display).

![Screenshot 2024-11-12 183610](https://github.com/user-attachments/assets/dcffb87c-9006-45bd-9982-f80752a29e32)

**Comment by amnweb** [comment]
This
![image](https://github.com/user-attachments/assets/574c20cc-3888-4e4d-bcba-aea69feb3780)

**Comment by JoshMuscat** [comment]
> This? ![image](https://private-user-images.githubusercontent.com/16545063/385192464-574c20cc-3888-4e4d-bcba-aea69feb3780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjE4NTIsIm5iZiI6MTczMTQ2MTU1MiwicGF0aCI6Ii8xNjU0NTA2My8zODUxOTI0NjQtNTc0YzIwY2MtMzg4OC00ZTRkLWJjYmEtYWVhNjlmZWIzNzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAxMzIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YWYyMDY0ODMwZThiNGNhZGQ3Y2JlZjhkOTBhOGQ5ZmI1ODNkYmNiOTViOGM2OWYyNzAzZThmODIxOTlkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9LKLUKtIhRFM27hgXhdL72BtFcgAdw5PElv5v54-R3o)

Yes! That's the one

**Comment by amnweb** [comment]
I can't reproduce this, for me, it still looks ok.
![image](https://github.com/user-attachments/assets/f9bec57d-ec49-4257-a893-d870636f7367)

Can you write step by step as well your resolution and DPI?

**Comment by JoshMuscat** [comment]
Display Resolution: 3840 x 2160
My monitor's PPI is 163 pixels per inch, however my monitor's scale is set to 175% (in settings)

This line only appears when I'm using a Firefox window that is not full-size. (i.e. if the window is any size but full)

**Comment by amnweb** [comment]
> Display Resolution: 3840 x 2160 My monitor's PPI is 163 pixels per inch, however my monitor's scale is set to 175% (in settings)
> 
> This line only appears when I'm using a Firefox window that is not full-size. (i.e. if the window is any size but full)
> 
> Edit: I just checked, and when the monitor is set to 100% or 150% scale, the line is not there. But as soon as it is set to 175%, it appears.

Can you try now? I have tried scaling 175%, and for me, it now looks fine, but I have a different resolution.

**Comment by JoshMuscat** [comment]
That worked! Thanks legend.

Love Firefox Plus, and appreciate your work! Also, I designed this simple new tab that works well for me and the overall Firefox Plus look. Just wanted to share it before you close this issue.

![new_tab](https://github.com/user-attachments/assets/48941224-342e-4223-ac2e-e6f70fa9169f)


Thanks again!
