### ISSUE TITLE
no space above tabs

### ISSUE THREAD

**Issue by t6rtar** [amnweb/firefox-plus#25]
**Describe the bug**
there is no gap between the top and the tabs and icons are black.

**To Reproduce**
install firefox plus

**Screenshots or video**
Add screenshots or video to help explain your problem.
![{63810A32-1BCC-4F47-89BB-55A52C5E13CC}](https://github.com/user-attachments/assets/4c5f47f5-1fa3-4f05-80dd-37f436046398)

**Firefox version (please complete the following information):**
132.0.2

**Additional context**

**Comment by amnweb** [comment]
Can you try set default dark Firefox theme ?
About that space above tab when is maximized https://github.com/amnweb/firefox-plus/issues/18

**Comment by t6rtar** [comment]
space has been fixed but the black icons are still there

**Comment by amnweb** [comment]
> space has been fixed but the black icons are still there even with default theme
> 

Please post a screenshot with default dark theme and this icons problem.

**Comment by t6rtar** [comment]
![{28DF07F1-F59D-4E88-AF64-096DC6B6671F}](https://github.com/user-attachments/assets/bc21371e-3d0c-4465-9467-4b85af96a8c8)

**Comment by amnweb** [comment]
This is how Firefox Plus should look, I don't know what you have installed there that messed up styles.

![image](https://github.com/user-attachments/assets/0d7b2f8b-049a-4595-a903-7d1a09e18db1)

**Comment by t6rtar** [comment]
just fixed it by adding the user.js content to my current one since i'm using betterfox. i can't read direction lmao

**Comment by amnweb** [comment]
So if is fixed we can close this issue ?
