### ISSUE TITLE
the latest firefox 133.0 version broke this

### ISSUE THREAD

**Issue by zyanifa** [amnweb/firefox-plus#26]

**Comment by amnweb** [comment]
Yeah again.

**Comment by Popslip** [comment]
such a shame they keep doing this, will be keeping my eye out to see if it's updated tho. i love this theme

**Comment by amnweb** [comment]
I will update tomorrow for day or two files, 90% is done

![Screenshot 2024-11-28 202415](https://github.com/user-attachments/assets/9ec97b04-6909-40a2-a8b7-e9f2d008df94)

**Comment by amnweb** [comment]
Updated.
