### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by advanced03** [amnweb/firefox-plus#28]
Is this theme supposed to be dark mode only? 

Love what you guys have done, but it's stuck in dark mode even with automatic mode enabled and my system being in light mode.

**Comment by amnweb** [comment]
I have no idea :D 
I use dark mode all the time and everywhere, not just Firefox. Anyway, does Firefox 133 change theme when you set auto without FF Plus?

**Comment by advanced03** [comment]
> I have no idea :D I use dark mode all the time and everywhere, not just Firefox. Anyway, does Firefox 133 change theme when you set auto without FF Plus?

Even on Auto it stays dark for some reason.

**Comment by amnweb** [comment]
> > I have no idea :D I use dark mode all the time and everywhere, not just Firefox. Anyway, does Firefox 133 change theme when you set auto without FF Plus?
> 
> Even on Auto it stays dark for some reason.

So problem is Firefox.

**Comment by advanced03** [comment]
> > > I have no idea :D I use dark mode all the time and everywhere, not just Firefox. Anyway, does Firefox 133 change theme when you set auto without FF Plus?
> > 
> > 
> > Even on Auto it stays dark for some reason.
> 
> So problem is Firefox

That's the weird thing if I remove the theme it works again

**Comment by amnweb** [comment]
> That's the weird thing if I remove the theme it works again

I will check when I have time

**Comment by advanced03** [comment]
Thank you very much, really like what you did. It's like the edge frfox theme but better.

**Comment by advanced03** [comment]
> Can you go to `about:config` find `ui.systemUsesDarkTheme` and delete it. Restart Firefox and try.

I think that worked, thank you very much!

**Comment by advanced03** [comment]
> Can you go to `about:config` find `ui.systemUsesDarkTheme` and delete it. Restart Firefox and try.

Last question how do you disable tab restoration? Even after i untick it it still restores tabs and gets reticked
