### ISSUE TITLE
Inactive buttons

### ISSUE THREAD

**Issue by imanubdesigner** [amnweb/firefox-plus#29]
**Describe the bug**

I don't think it's a bug, maybe it's intentional or an oversight, but it would be nice if when buttons aren't clickable (for whatever reason), they became "opaque".

**Screenshots or video**

_This screenshot shows when a button is active_

![QgOopSx7e9](https://github.com/user-attachments/assets/5d24a610-c818-4d8b-84c3-1e1494ac44b7)

----------------------------------

This, instead, when it is not possible to interact with the button: as you can see it remains with the writing very visible, instead it would be more suitable (in my opinion, obviously) to have them a little less visible, almost with the same color as the background.

![GuBzcvTduW](https://github.com/user-attachments/assets/7a7d3422-e935-460a-ba28-adafac12759a)

**Firefox version (please complete the following information):**
 - Version [133.0.3]

**Comment by amnweb** [comment]
Maybe we can just add opacity like this?
![image](https://github.com/user-attachments/assets/4b7335ef-dded-4a1e-af8b-520d739bc269)

**Comment by imanubdesigner** [comment]
Yeah! This is great! <3 Thank you!

**Comment by amnweb** [comment]
Ok, all is fixed, only this from screenshot I don't know what it is and how to get this item in the menu.
![image](https://github.com/user-attachments/assets/0041320a-6a54-4454-a31b-5c8a4fb16b77)

**Comment by imanubdesigner** [comment]
> Ok, all is fixed, only this from screenshot I don't know what it is and how to get this item in the menu. ![image](https://private-user-images.githubusercontent.com/16545063/395900229-0041320a-6a54-4454-a31b-5c8a4fb16b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyOTk4ODMsIm5iZiI6MTczNDI5OTU4MywicGF0aCI6Ii8xNjU0NTA2My8zOTU5MDAyMjktMDA0MTMyMGEtNmE1NC00NDU0LWEzMWItNWM4YTRmYjE2Yjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDIxNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YzI4ZWY2NjcwNzgxN2QyYTU2YjczMjFkNDQ4MThiMDBjMDQ3NTdkYTNjZjRjZDE4OTBiN2YwYmVhZWNkYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JGOUHBEMoDFqihLv6PkFpXlS4gE0oKW5tyOP5SmijVU)

Great! 

Cerca in una finestra anonima (Search in an anonymous window), but i can't figure out where it's coming from. It doesn't seem to be related to the translation, it's referring to the text. If i click on a reddit title (for example), it appears. But if i click on the image of the same post, it doesn't.

**Comment by amnweb** [comment]
Strange I don't have this :(
Here is what I can see when i right click on reddit title

![image](https://github.com/user-attachments/assets/cd423fa0-a384-40a8-a7d8-2989612eaed8)

**Comment by imanubdesigner** [comment]
> Strange I don't have this :( Here is what I can see when i right click on reddit title
> 
> ![image](https://private-user-images.githubusercontent.com/16545063/395901861-cd423fa0-a384-40a8-a7d8-2989612eaed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMDA2MjksIm5iZiI6MTczNDMwMDMyOSwicGF0aCI6Ii8xNjU0NTA2My8zOTU5MDE4NjEtY2Q0MjNmYTAtYTM4NC00MGE4LWE3ZDgtMjk4OTYxMmVhZWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDIyMDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZTIyMWNkZDJmOWJhODY5ZjQzMTMyZmJkMGNiNGU1YTM3OGY4YjVmMzU3NDQxM2Y5MDliNTk0MjAwMTc0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z8mQHHjDkgxMm61Efih4IbOxW7zrAXuL2aNX24KG05U)

Maybe it's something to do with the translation? I can't figure it out.

**Comment by amnweb** [comment]
Probably this is a `context-searchselect-private`, can you update your CSS and try?

**Comment by imanubdesigner** [comment]
> Probably this is a `context-searchselect-private`, can you update your CSS and try?

Yeah! Sure. I don't know what css you need, so I posted everything for you.

[chrome-firefoxplus.zip](https://github.com/user-attachments/files/18142389/chrome-firefoxplus.zip)


I also tried setting the browser language to English, but that entry always remains in Italian.

![fNGPPn7G0x](https://github.com/user-attachments/assets/d32197b3-0d22-4aef-9c5e-acc21c606f1f)

**Comment by amnweb** [comment]
I mean get new CSS from this repo, I have updated all this, but I can't test it because I don't have it and I don't know how to get these menu items which you have xD Simple, just reinstall FF Plus and try

**Comment by imanubdesigner** [comment]
> I mean get new CSS from this repo, I have updated all this, but I can't test it because I don't have it and I don't know how to get these menu items which you have xD Simple, just reinstall FF Plus and try

I'm so sorry about that. I'm tired. I'll try it right away

**Comment by imanubdesigner** [comment]
P E R F E C T! Thank you so much! 


FIREFOX IN ENGLISH:

![nQC0xqHHt6](https://github.com/user-attachments/assets/f9e268cd-33f0-4782-a749-fda651178a9b)


FIREFOX IN ITALIAN:

![Nn0jT4xJJz](https://github.com/user-attachments/assets/d0f5c4d1-24c5-4dfd-a9c1-2ca3aa2bb0ed)


You can close the report. **THANK YOU SO MUCH!**
The best firefox theme!

If I find something strange, I'll let you know! Have a great day / evening
