### ISSUE TITLE
Some questions regarding a few color things on the new tab page

### ISSUE THREAD

**Issue by Kindanoob1664** [amnweb/firefox-plus#30]
Hi!

I took your theme, but wanted to add a custom color to the weather icon, so I added the following to my userChrome.css file:
`@-moz-document url(chrome://browser/content/browser.xul), url(about:newtab), url(about:home) {
	.weatherCard {
		background-color: rgba(0, 52, 143, 0.75) !important
		}`

This is what the end result is:
![image](https://github.com/user-attachments/assets/65c3739f-e751-480f-9fa4-c757e0ef1f48)

Do you know which element to alter in the css so that the left color is applied to the full thing?

And for the new tab page, do you know how to get rid of the settings button in the top right?

Edit:
Oh, and one more thing: 
I saw this on another issue, but don't know how to solve this. There's a line underneath the tab (see image)
![image](https://github.com/user-attachments/assets/f6ba8c89-6be3-4ca7-8595-15dd60fc9d63)

Thank you in advance

**Comment by Kindanoob1664** [comment]
Update: I decided to just use my old new tab page (basically, reverted my old userContent.css file.

Do you still have ea solution for the line underneath the tab?

**Comment by amnweb** [comment]
I can't test now and don't know where is this border, I can't see it, but can you try something like 

```
#nav-bar {
  border-top: 0 !important
}
```

**Comment by Kindanoob1664** [comment]
ok yup that worked. Thanks for the help

**Comment by Kindanoob1664** [comment]
.
