### ISSUE TITLE
Video player display issue

### ISSUE THREAD

**Issue by kifrud** [amnweb/firefox-plus#4]
OS/Version: Windows 10 Mozilla Firefox Developer Edition

Looks with theme:

![image](https://github.com/amnweb/firefox-plus/assets/81026431/085cf996-6f75-44b4-b54d-3a606869d329)

...and without:

![image](https://github.com/amnweb/firefox-plus/assets/81026431/a9560bd8-485a-4298-b475-528452e3697f)

**Comment by amnweb** [comment]
Can you share more information please, or some demo of problematic player or page?

**Comment by kifrud** [comment]
> Can you share more information please, or some demo of problematic player or page?


https://github.com/amnweb/firefox-plus/assets/81026431/b9b5601c-a11a-4124-8636-826aac0470a4

the site is [rezka.ag](https://rezka.ag/animation/fantasy/62195-friren-provozhayuschaya-v-posledniy-put-2023.html)

**Comment by amnweb** [comment]
Please try now, should be fixed.

**Comment by kifrud** [comment]
> Please try now, should be fixed.

Yeah, the bug is now fixed. Thank you a lot!
