### ISSUE TITLE
YouTube music card has different background

### ISSUE THREAD

**Issue by kifrud** [amnweb/firefox-plus#5]
OS: Windows 10 22H2
Firefox: Developer Edition 124.0b5 (64-bit)

On search result page there is different background on the main card with the theme:
![image](https://github.com/amnweb/firefox-plus/assets/81026431/d5f4799a-04fc-4b1f-bcd7-09e9abae4f40)

...and without it has background:
![image](https://github.com/amnweb/firefox-plus/assets/81026431/f5c7edf8-cb10-4d6f-a40a-f56961c0d724)
(don't mind the font-size that's because of window scaling)

**Comment by amnweb** [comment]
Hello, thanks for reporting this bug, for quick fix just open **userContent.css** and comment or remove this line `@import url("content/card-container.css")`, restart firefox.
