### ISSUE TITLE
Rounded corners not applied to bookmark bar

### ISSUE THREAD

**Issue by Xtrems876** [amnweb/firefox-plus#6]
OS: Linux

There are no rounded corners for the bookmark bar, which means that if you set bookmark autohide to "false", and rounded corners to "true", the top rounded corners are always hidden behind the bookmark bar.

Current behaviour:
![obraz](https://github.com/amnweb/firefox-plus/assets/122691482/0cab77d2-faeb-447a-9dfc-9d8e475ab7ba)

Expected behaviour:
![Bez nazwy](https://github.com/amnweb/firefox-plus/assets/122691482/15b6ce0e-08fa-40aa-8181-ec93c1a586a3)

**Comment by amnweb** [comment]
Fixed
