### ISSUE TITLE
No close, minimize, maximize button

### ISSUE THREAD

**Issue by Kamrulhasan12345** [amnweb/firefox-plus#8]
After installing firefox-plus,
I can see no close, minimize and maximize button, like this:
![no close_minimize, maximize button](https://i.imgur.com/4ZsMxzu.png)

**Comment by amnweb** [comment]
Which OS ?

**Comment by Kamrulhasan12345** [comment]
Windows 11 23H2
Firefox Developer Edition 125

**Comment by Kamrulhasan12345** [comment]
Don't know why, but looks like 
![image](https://github.com/amnweb/firefox-plus/assets/32530625/ca0e732e-0c8a-4c6f-9aaa-b060f1e8aefb)
this is not working as expected,
apparently it positions the buttonbox absolute and tries to change their height to match the navbar and hides the titlebar using height = 0 in #titlebar css. But while titlebar is successfully hidden, the buttonbox doesn't appear when it is not over the titlebar.

**Comment by amnweb** [comment]
Just tested and all is working fine

![Screenshot 2024-04-13 215142](https://github.com/amnweb/firefox-plus/assets/16545063/e0ffc40d-dac4-4caa-8d7e-a4e39db06669)

**Comment by Kamrulhasan12345** [comment]
Don't know why, but looks like 
![image](https://github.com/amnweb/firefox-plus/assets/32530625/ca0e732e-0c8a-4c6f-9aaa-b060f1e8aefb)
this is not working as expected,
apparently it positions the buttonbox absolute and tries to change their height to match the navbar and hides the titlebar using height = 0 in #titlebar css. But while titlebar is successfully hidden, the buttonbox doesn't appear when it is not over the titlebar.

(My situation is while sidebar is enabled

**Comment by Kamrulhasan12345** [comment]
I have sidebar enabled.

**Comment by amnweb** [comment]
Open about:support > Profile Folder > Chrome folder and userChrome.css

Add this line at the end and Clear startup cache…
```
#nav-bar:not([tabs-hidden="true"]) {
  position: inherit !important;
}
```
