### ISSUE TITLE
bookmarks autohide，no working

### ISSUE THREAD

**Issue by san-ren** [amnweb/firefox-plus#9]
""fp.tweak.autohide-bookmarks" is true,but it dosen't work.
Another "[autohide_bookmarks_toolbar.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_toolbar.css)" is normal,I'd appreciate it  if you could fix this bug.

**Comment by amnweb** [comment]
Set Bookmarks Toolbar > Always Show

![Screenshot 2024-04-16 174342](https://github.com/amnweb/firefox-plus/assets/16545063/d945abda-fcb5-41d7-b00f-e87e1e41b0a3)

**Comment by san-ren** [comment]
yeah,my setting is "Always Show" from beginning to end. But it just can't autohide.
![图片](https://github.com/amnweb/firefox-plus/assets/86779955/616f42bd-ed9f-4de2-8521-a255c8b39f58)

If  everything is fine in your place,there must be something wrong with me.But I'm new to userchrome,  I'm not sure what's my problem.
I can use another autohide-css,
thank you
